### ISSUE TITLE
Consider adding `wemake-django-template`

### ISSUE THREAD

**Issue by sobolevn** [guardrailsio/awesome-python-security#1]
Hi, thanks for this list! It is awesome.

I would like to ask if that's appropriate to add our `django`-project template to this list?

Why do I think that it belongs here? Well for a couple of reasons.
1. This template is heavily oriented on security. Check out the source code to find out: https://github.com/wemake-services/wemake-django-template
2. Like really, we care about security. Check out our security docs: https://wemake-django-template.readthedocs.io/en/latest/pages/template/security.html
3. We use a lot of stuff from this awesome list already: `bandit`, `safety`, `snyk`, `secure.py`, and many more

I think that there are other templates for `django` / `flask` / etc that should also be added.
What do you think?

**Comment by kytwb** [comment]
@sobolevn sounds good to me, PR welcome! 😄
